### ISSUE TITLE
Install instructions: ruby 3.x caveat

### ISSUE THREAD

**Issue by habere-et-dispertire** [exercism/snippet-extractor#55]
After a major ruby upgrade from 2.x to 3.x, the `bundle install` fails with:

~~~bash
$ bundle install 

Fetching gem metadata from https://rubygems.org/.........
Your bundle is locked to minitest (5.14.2) from rubygems repository https://rubygems.org/ or installed locally, but that version can
no longer be found in that source. That means the author of minitest (5.14.2) has removed it. You'll need to update your bundle to a
version other than minitest (5.14.2) that hasn't been removed in order to install.
~~~

I've downgraded, and it works fine. Something to perhaps note in the install instructions?

**Comment by iHiD** [comment]
Thanks for reporting. 

This repo is locked to ruby 2.6.6 as per the [Ruby Version](https://github.com/exercism/snippet-extractor/blob/main/.ruby-version) so it's recommended(/required) you have that installed. Multiple versions of ruby can be installed via rbenv, rvm, or ruby-install and chruby (the later pair of which I use). I'm going to close this as there's no guarantee this repo would work at all yet with 3.1.0. That said, if you'd like to PR an update to Ruby 3.1.0 with the `.ruby-version`, `Gemfile` and CI updated, that would be welcomed :)
